CREATE TABLE IF NOT EXISTS JOGADORES (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    NOME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    TELEFONE VARCHAR(250),
    CODINOME VARCHAR(250) NOT NULL,
    grupoCodinome VARCHAR(250) NOT NULL,
    CONSTRAINT unique_codinome_grupo UNIQUE (codinome, grupo_codinome)
);